"""Shared AI contracts, enums, and base detector interface."""

from ai.common.base import BaseDetector, ModelNotLoadedError, StubPredictionError
from ai.common.types import (
    BoundingRect,
    Category,
    Confidence,
    ConfidenceBreakdown,
    EvidenceItem,
    ExplainableReport,
    FusionInput,
    FusionOutput,
    PredictionResult,
    RuleExplanation,
    RuleHit,
    RuleResult,
    RuleTrace,
    ScanPayload,
    TextPrediction,
    TrainResult,
    EvalMetrics,
    VisionFeatures,
)

__all__ = [
    "BaseDetector",
    "ModelNotLoadedError",
    "StubPredictionError",
    "BoundingRect",
    "Category",
    "Confidence",
    "ConfidenceBreakdown",
    "EvidenceItem",
    "ExplainableReport",
    "FusionInput",
    "FusionOutput",
    "PredictionResult",
    "RuleExplanation",
    "RuleHit",
    "RuleResult",
    "RuleTrace",
    "ScanPayload",
    "TextPrediction",
    "TrainResult",
    "EvalMetrics",
    "VisionFeatures",
]
